{{- if .Values.webhookserver.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "netguard-chart.serviceAccountName" . }}-webhookserver
  labels:
    app.kubernetes.io/component: webhookserver
    {{- include "netguard-chart.labels" . | nindent 4 }}
  {{- with .Values.webhookserver.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.webhookserver.serviceAccount.automount }}
{{- end }}
