{{ if .Values.webResources.enabled }}
---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomFormsPrefill
metadata:
  name: netguard.sgroups.io.v1beta1.hosts
spec:
  customizationId: default-/netguard.sgroups.io/v1beta1/hosts
  values:
    - path:
        - metadata
      value: 
        generateName: dynamic-
    - path:
        - spec
      value:
        uuid: ""
{{ end }}
