{{- if .Values.apiserver.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "netguard-chart.fullname" . }}-apiserver
rules:
  - apiGroups:
      - apiregistration.k8s.io
    resources:
      - apiservices
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
      - validatingadmissionpolicies
      - validatingadmissionpolicybindings
      - validatingadmissionwebhooks
      - mutatingadmissionwebhooks
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - netguard.sgroups.io
    resources:
      - services
      - addressgroups
      - addressgroupbindings
      - addressgroupportmappings
      - rules2s
      - servicealiases
      - addressgroupbindingpolicies
      - ieagagrules
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch

  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - extension-apiserver-authentication
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
      - selfsubjectaccessreviews
      - tokenreviews
    verbs:
      - create

  - apiGroups:
      - flowcontrol.apiserver.k8s.io
    resources:
      - flowschemas
      - prioritylevelconfigurations
    verbs:
      - get
      - list
      - watch
{{- end }}
