{{- with .Values.appSpec.applications.ngapiserver }}
  {{- if .enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "netguard-chart.fullname" . }}-apiserver
  namespace: {{ $.Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
  {{- end }}
{{- end }}
