{{- if .Values.apiserver.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "netguard-chart.serviceAccountName" . }}-apiserver
  labels:
    app.kubernetes.io/component: apiserver
    {{- include "netguard-chart.labels" . | nindent 4 }}
  {{- with .Values.apiserver.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.apiserver.serviceAccount.automount }}
{{- end }}
