
{{- $dbUrl      := "" }}
{{- $dbPort     := "" }}
{{- $dbName     := "" }}
{{- $dbUsername := "" }}
{{- $dbPassword := "" }}
{{- $dbSSL      := "disable" }}
{{- $extPG := .Values.externalDatabase -}}
{{- $pg := .Values.postgresql -}}


{{- if $extPG.enabled }}
{{- $dbUrl      = $extPG.url }}
{{- $dbPort     = $extPG.port }}
{{- $dbName     = $extPG.database }}
{{- $dbUsername = $extPG.username }}
{{- $dbPassword = $extPG.password }}
{{- $dbSSL      = $extPG.sslmode }}
{{- else }}
{{- $dbUrl      = printf "%s-postgresql.%s.svc" $.Release.Name $.Release.Namespace }}
{{- $dbPort     = $pg.primary.service.ports.postgresql }}
{{- $dbName     = $pg.auth.database }}
{{- $dbUsername = $pg.auth.username }}
{{- $dbPassword = $pg.auth.password }}
{{ end }}

{{- if .Values.backend.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netguard-chart.fullname" . }}-database
  namespace: {{ .Release.Namespace }}
data: 
  DATABASE_URL:             "{{ $dbUrl }}"
  DATABASE_PORT:            "{{ $dbPort }}"
  DATABASE_NAME:            "{{ $dbName }}"
  DATABASE_USERNAME:        "{{ $dbUsername }}"
  DATABASE_PASSWORD:        "{{ $dbPassword }}"
  DATABASE_SSLMODE:         "{{ $dbSSL }}"
  DATABASE_CONNECTION_URL:  "postgres://{{ $dbUsername }}:{{ $dbPassword }}@{{ $dbUrl }}:{{ $dbPort }}/{{ $dbName }}?sslmode={{ $dbSSL }}"
{{- end }}
