{{ $projectResource       := .Values.webResources.projectResource }}
{{ $instanceResource      := .Values.webResources.instanceResource }}
{{ $instanceResourcePath  := printf "%s/%s/%s" $instanceResource.apiGroup $instanceResource.apiVersion $instanceResource.resourceName }}

{{ if ($projectResource.deployWebResources) }}
---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: stock-cluster-project
spec:
  additionalPrinterColumns:
    - jsonPath: .metadata.name
      name: Name
      type: factory
      customProps:
        disableEventBubbling: true
        items:
        - type: antdFlex
          data:
            id: resource-badge-link-row
            direction: row
            align: center
            gap: 6
          children:
            - type: ResourceBadge
              data:
                id: example-resource-badge
                value: Project
            - type: antdLink
              data:
                id: name-link
                text: "{reqsJsonPath[0]['.metadata.name']['-']}"
                href: "/{1}/{2}/{reqsJsonPath[0]['.metadata.name']['-']}/api-table/in-cloud.io/v1alpha1/instances"

    - jsonPath: .spec.alias
      name: Alias
      type: string

    - name: Description
      jsonPath: .spec.description
      type: factory
      customProps:
        disableEventBubbling: true
        items:
          - type: parsedText
            data:
              id: name-postfix
              text: '{reqsJsonPath[0][".spec.description"]["-"]}'
              style:
                display: block
                width: "300px"

    - jsonPath: .metadata.creationTimestamp
      name: Created
      type: factory
      customProps:
        disableEventBubbling: true
        items:
        - type: antdFlex
          data:
            id: time-block
            align: center
            gap: 6
          children:
            - type: antdText
              data:
                id: time-icon
                text: "🌐"
            - type: parsedText
              data:
                id: time-value
                text: "{reqsJsonPath[0]['.metadata.creationTimestamp']['-']}"
                formatter: timestamp
  additionalPrinterColumnsTrimLengths:
    - key: Name
      value: 64
  additionalPrinterColumnsUndefinedValues: []
  id: "stock-cluster-/{{ $projectResource.apiGroup }}/{{ $projectResource.apiVersion }}/{{ $projectResource.resourceName }}"
{{ end }}
