{{- $extIssuer    := .Values.tls.certmanager.existingIssuer -}}

{{- if eq .Values.tls.certSource "certmanager" }}
{{- if or (not $extIssuer.kind) (not $extIssuer.name) }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "netguard-chart.fullname" . }}-selfsigned-internal
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netguard-chart.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
{{- end }}
