{{ if .Values.webResources.enabled }}
---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomFormsOverride
metadata:
  name: netguard.sgroups.io.v1beta1.servicealiases
spec:
  hidden:
    - - apiVersion
    - - kind
    - - status
    - - networks
    - - metadata
      - creationTimestamp
    - - metadata
      - deletionGracePeriodSeconds
    - - metadata
      - deletionTimestamp
    - - metadata
      - finalizers
    - - metadata
      - generateName
    - - metadata
      - generation
    - - metadata
      - managedFields
    - - metadata
      - labels
    - - metadata
      - annotations
    - - metadata
      - ownerReferences
    - - metadata
      - resourceVersion
    - - metadata
      - selfLink
    - - metadata
      - uid
    - - spec
      - serviceRef
      - apiVersion
    - - spec
      - serviceRef
      - kind
    - - spec
      - serviceRef
      - namespace
  customizationId: default-/netguard.sgroups.io/v1beta1/servicealiases
  schema:
    properties:
      metadata:
        properties:
          namespace:
            customProps:
              keysToLabel:
                {{ .Values.webResources.namespaceSelectorLabelPath | toYaml | nindent 16 }}
              keysToValue:
                - metadata
                - name
              valueUri: "{{ .Values.webResources.namespaceValueUri }}"
            type: listInput
        type: object
      spec:
        description: ServiceAliasSpec defines the desired state of ServiceAlias.
        properties:
          serviceRef:
            description:
              ServiceRef is a reference to the Service resource this
              alias points to
            properties:
              apiVersion:
                description: APIVersion of the referenced object
                enum:
                  - netguard.sgroups.io/v1beta1
                type: string
              kind:
                description: Kind of the referenced object
                enum:
                  - Service
                type: string
              name:
                customProps:
                  keysToLabel:
                    - metadata
                    - name
                  keysToValue:
                    - metadata
                    - name
                  mode: tag
                  valueUri: /api/clusters/{cluster}/k8s/apis/netguard.sgroups.io/v1beta1/namespaces/{relatedFieldValue}/services
                  relatedValuePath:
                  - metadata
                  - namespace
                type: listInput
              namespace:
                customProps:
                  keysToLabel:
                    - status
                    - addressGroupName
                  keysToValue:
                    - metadata
                    - name
                  mode: tag
                  valueUri: /api/clusters/{cluster}/k8s/api/v1/namespaces
                type: listInput
            required:
              - apiVersion
              - kind
              - name
            type: object
        required:
          - serviceRef
        type: object
  strategy: merge
{{ end }}
