{{ if .Values.webResources.enabled }}
---
apiVersion: front.in-cloud.io/v1alpha1
kind: Breadcrumb
metadata:
  name: stock-project-factory-hbf-service-details
spec:
  id: "stock-project-factory-hbf-service-details"
  breadcrumbItems:
    - key: services
      label: "netguard.sgroups.io/v1beta1/services"
      link: "/openapi-ui/{cluster}/{namespace}/api-table/netguard.sgroups.io/v1beta1/services"
    - key: service
      label: "{9}"

---
apiVersion: front.in-cloud.io/v1alpha1
kind: Breadcrumb
metadata:
  name: stock-instance-factory-hbf-service-instance-details
spec:
  id: "stock-instance-factory-hbf-service-instance-details"
  breadcrumbItems:
    - key: services
      label: "netguard.sgroups.io/v1beta1/services"
      link: "/openapi-ui/{cluster}/{namespace}/{syntheticProject}/api-table/netguard.sgroups.io/v1beta1/services"
    - key: service
      label: "{10}"
{{ end }}
